task:
  name: "Win64 native [vs2022]"
  windows_container:
    cpu: 2
    image: cirrusci/windowsservercore:visualstudio2022
  env:
    x64_NATIVE_TOOLS: '"C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvars64.bat"'
    CI_VCPKG_TAG: '2023.01.09'
    VCPKG_DOWNLOADS: 'C:\Users\ContainerAdministrator\AppData\Local\vcpkg\downloads'
    VCPKG_DEFAULT_BINARY_CACHE: 'C:\Users\ContainerAdministrator\AppData\Local\vcpkg\archives'
    WRAPPED_CL: 'C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\ci\test\wrapped-cl.bat'
    IgnoreWarnIntDirInTempDetected: 'true'
  choco_script:
    - choco install --yes --no-progress ccache --version=4.7.4
  ccache_script:
    - ccache --version
    - ccache --version --shimgen-log
  configure_script:
    - '%x64_NATIVE_TOOLS%'
    - cmake --version
    - cmake -S . -B build
  build_release_script:
    - '%x64_NATIVE_TOOLS%'
    - cmake --build build --config Release
  build_debug_script:
    - '%x64_NATIVE_TOOLS%'
    - cmake --build build --config Debug
