task:
  name: 'environment'
  container:
    image: ubuntu:jammy
    cpu: 1
  print_env_script: |
    echo CI=$CI
    echo CIRRUS_CI=$CIRRUS_CI
    echo CI_NODE_INDEX=$CI_NODE_INDEX
    echo CI_NODE_TOTAL=$CI_NODE_TOTAL
    echo CONTINUOUS_INTEGRATION=$CONTINUOUS_INTEGRATION
    echo CIRRUS_API_CREATED=$CIRRUS_API_CREATED
    echo CIRRUS_BASE_BRANCH=$CIRRUS_BASE_BRANCH
    echo CIRRUS_BASE_SHA=$CIRRUS_BASE_SHA
    echo CIRRUS_BRANCH=$CIRRUS_BRANCH
    echo CIRRUS_BUILD_ID=$CIRRUS_BUILD_ID
    echo CIRRUS_CHANGE_IN_REPO=$CIRRUS_CHANGE_IN_REPO
    echo CIRRUS_CHANGE_MESSAGE=$CIRRUS_CHANGE_MESSAGE
    echo CIRRUS_CHANGE_TITLE=$CIRRUS_CHANGE_TITLE
    echo CIRRUS_CRON=$CIRRUS_CRON
    echo CIRRUS_DEFAULT_BRANCH=$CIRRUS_DEFAULT_BRANCH
    echo CIRRUS_DOCKER_CONTEXT=$CIRRUS_DOCKER_CONTEXT
    echo CIRRUS_LAST_GREEN_BUILD_ID=$CIRRUS_LAST_GREEN_BUILD_ID
    echo CIRRUS_LAST_GREEN_CHANGE=$CIRRUS_LAST_GREEN_CHANGE
    echo CIRRUS_PR=$CIRRUS_PR
    echo CIRRUS_PR_DRAFT=$CIRRUS_PR_DRAFT
    echo CIRRUS_PR_LABELS=$CIRRUS_PR_LABELS
    echo CIRRUS_TAG=$CIRRUS_TAG
    echo CIRRUS_OIDC_TOKEN=$CIRRUS_OIDC_TOKEN
    echo CIRRUS_TASK_NAME=$CIRRUS_TASK_NAME
    echo CIRRUS_TASK_ID=$CIRRUS_TASK_ID
    echo CIRRUS_RELEASE=$CIRRUS_RELEASE
    echo CIRRUS_REPO_CLONE_TOKEN=$CIRRUS_REPO_CLONE_TOKEN
    echo CIRRUS_REPO_NAME=$CIRRUS_REPO_NAME
    echo CIRRUS_REPO_OWNER=$CIRRUS_REPO_OWNER
    echo CIRRUS_REPO_FULL_NAME=$CIRRUS_REPO_FULL_NAME
    echo CIRRUS_REPO_CLONE_URL=$CIRRUS_REPO_CLONE_URL
    echo CIRRUS_USER_COLLABORATOR=$CIRRUS_USER_COLLABORATOR
    echo CIRRUS_USER_PERMISSION=$CIRRUS_USER_PERMISSION
    echo CIRRUS_HTTP_CACHE_HOST=$CIRRUS_HTTP_CACHE_HOST
    echo GITHUB_CHECK_SUITE_ID=$GITHUB_CHECK_SUITE_ID
    echo CIRRUS_ENV=$CIRRUS_ENV
    echo CIRRUS_ENV_SENSITIVE=$CIRRUS_ENV_SENSITIVE
