version: 2.1

orbs:
  win: circleci/windows@5.0

jobs:
  build:
    executor:
      name: win/server-2022
      size: medium  # default, 4 CPU / 15 GB RAM.
      shell: 'cmd.exe'
    environment:
      - CCACHE_URI: "https://github.com/ccache/ccache/releases/download/v4.8.2/ccache-4.8.2-windows-x86_64.zip"
    steps:
      - run:
          name: "Developer Environment"
          command: C:\"Program Files (x86)"\"Microsoft Visual Studio"\2022\BuildTools\VC\Auxiliary\Build\vcvars64.bat && echo %PATH% && cl.exe /?

workflows:
  my-workflow:
    jobs:
      - build
