version: 2.1
orbs:
  win: circleci/windows@5.0

commands:
  prepare_ccache_exe:
    description: "Download ccache archive"
    steps:
      - run: Invoke-WebRequest -Uri "$($env:CCACHE_URI)" -OutFile "ccache.zip"
      - run: Expand-Archive -Path "ccache.zip" -DestinationPath "C:\"
      - run: C:\ccache-4.8.2-windows-x86_64\ccache.exe --version
      - run: New-Item -ItemType Directory -Path "C:\ccache"
      - run: Copy-Item -Path "C:\ccache-4.8.2-windows-x86_64\ccache.exe" -Destination "C:\ccache\cl.exe"
      - run: '"C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvars64.bat"'
      # - run: C:\"Program Files (x86)"\"Microsoft Visual Studio"\2022\BuildTools\VC\Auxiliary\Build\vcvars64.bat
      - run: C:\ccache\cl.exe /?
      # ccache: error: Could not find compiler "cl.exe" in PATH

jobs:
  build:
    executor: win/server-2022
    environment:
      - CCACHE_URI: "https://github.com/ccache/ccache/releases/download/v4.8.2/ccache-4.8.2-windows-x86_64.zip"
    steps:
      - run:
          name: "Cute Name :)"
          command: Write-Host 'Hello, Windows'
      - run: Get-Command msbuild
      # - run: Get-Command cl
      - run: Get-ChildItem -Path C:\"Program Files (x86)"
      - run: Get-ChildItem -Path C:\"Program Files (x86)"\"Microsoft Visual Studio"
      - run: Get-ChildItem -Path C:\"Program Files (x86)"\"Microsoft Visual Studio"\2022\BuildTools
      - run: Get-ChildItem -Path C:\"Program Files (x86)"\"Microsoft Visual Studio"\2022\BuildTools\VC\Tools\MSVC
      - run: Get-ChildItem -Path C:\"Program Files (x86)"\"Microsoft Visual Studio"\2022\BuildTools\VC\Tools\MSVC\14.36.32532\bin\HostX64\x64
      - run: Write-Host "$($env:PATH)"
      - run:
          shell: 'cmd.exe'
          command: |
            C:\"Program Files (x86)"\"Microsoft Visual Studio"\2022\BuildTools\VC\Auxiliary\Build\vcvars64.bat
            echo %PATH%
            cl.exe /?
      - prepare_ccache_exe

workflows:
  my-workflow:
    jobs:
      - build
